import {
  Circle, Document, G, Image, Line, Page, Path, Rect, StyleSheet, Svg,
  Text, Text as PdfSvgText, View,
} from "@react-pdf/renderer";
import { cloneElement, type ComponentType, type ReactElement, type ReactNode } from "react";
import {
  DEFAULT_REPORT_SECTION_IDS,
  type ReportDistributionRow, type ReportInjuryTypeFamily, type ReportMetric,
  type ReportModel, type ReportPatternRow, type ReportProfileRow,
  type ReportSectionId, type ReportSettingMetric, type SeasonComparisonMetric,
} from "@/lib/report-model-types";

export { DEFAULT_REPORT_SECTION_IDS } from "@/lib/report-model-types";
export type { ReportModel, ReportSectionId } from "@/lib/report-model-types";

// React PDF exposes the SVG text mark through the same runtime component as
// document text, while its bundled type currently omits the SVG font props.
const SvgText = PdfSvgText as unknown as ComponentType<Record<string, unknown>>;

const C = {
  navy: "#071C3B", navy2: "#102C55", ink: "#14233B", muted: "#64748B",
  line: "#D9E3EC", paper: "#F3F7FA", white: "#FFFFFF", cyan: "#02D5F0",
  mint: "#42D8B4", blue: "#72A7FF", amber: "#FFC45C", coral: "#EF7189",
  purple: "#A78BFA", lime: "#8BD450", orange: "#FB923C", red: "#D95656",
  green: "#2F8F62", grey: "#94A3B8",
} as const;
const PALETTE = [C.cyan, C.mint, C.blue, C.amber, C.coral, C.purple, C.lime, C.orange];
const SEVERITY_COLOURS: Record<string, string> = {
  zero_days_medical_attention_only: C.grey, one_day: C.cyan, two_to_three_days: C.cyan,
  four_to_seven_days: C.mint, eight_to_twenty_eight_days: C.amber,
  greater_than_twenty_eight_days: C.coral, unknown_or_censored: C.purple,
};
const CONTACT_COLOURS: Record<string, string> = { contact: C.purple, non_contact: C.orange, unknown: C.grey };
type ReportMetadata = { version: string; sourceGeneratedAt: string; exportedAt: string };

const styles = StyleSheet.create({
  page: { backgroundColor: C.paper, color: C.ink, fontFamily: "Helvetica", fontSize: 8, paddingHorizontal: 30, paddingBottom: 34 },
  cover: { backgroundColor: C.navy, color: C.white, fontFamily: "Helvetica", padding: 30 },
  header: { height: 40, paddingTop: 18, flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderBottomWidth: 1, borderBottomColor: C.line, marginBottom: 12 },
  headerBrand: { flexDirection: "row", alignItems: "center" }, headerCrest: { width: 20, height: 20, objectFit: "contain", marginRight: 7 },
  eyebrow: { color: C.cyan, fontFamily: "Helvetica-Bold", fontSize: 7, letterSpacing: 1.4, textTransform: "uppercase" },
  headerLabel: { color: C.muted, fontFamily: "Helvetica-Bold", fontSize: 7, letterSpacing: 0.8, textTransform: "uppercase" },
  title: { color: C.navy, fontFamily: "Helvetica-Bold", fontSize: 18, lineHeight: 1.05 },
  standfirst: { color: C.muted, fontSize: 8, lineHeight: 1.35, marginTop: 3, marginBottom: 9 },
  panel: { backgroundColor: C.white, borderRadius: 5, padding: 9, borderWidth: 1, borderColor: C.line },
  darkPanel: { backgroundColor: C.navy, borderRadius: 5, padding: 10, color: C.white },
  panelTitle: { color: C.navy, fontFamily: "Helvetica-Bold", fontSize: 9, letterSpacing: 0.2, marginBottom: 3 },
  panelNote: { color: C.muted, fontSize: 6.5, lineHeight: 1.3, marginBottom: 6 },
  split: { flexDirection: "row", marginHorizontal: -4 }, half: { width: "50%", paddingHorizontal: 4 }, third: { width: "33.333%", paddingHorizontal: 4 },
  footer: { position: "absolute", bottom: 13, left: 30, right: 30, flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: C.line, paddingTop: 5, color: C.muted, fontSize: 5.8 },
  coverFooter: { borderTopColor: "#294565", color: "#BED0E3" },
  metricGrid: { flexDirection: "row", flexWrap: "wrap", marginHorizontal: -3 }, metricCell: { padding: 3 },
  metricCard: { minHeight: 62, backgroundColor: C.white, borderRadius: 4, padding: 8, overflow: "hidden" },
  metricValue: { color: C.navy, fontFamily: "Helvetica-Bold", fontSize: 15 }, metricUnit: { color: C.muted, fontSize: 6.2, marginTop: 1 },
  metricLabel: { color: C.ink, fontFamily: "Helvetica-Bold", fontSize: 7.2, marginTop: 5 },
  legend: { flexDirection: "row", flexWrap: "wrap", marginTop: 4 }, legendItem: { flexDirection: "row", alignItems: "center", marginRight: 10, marginBottom: 3 },
  legendDot: { width: 5, height: 5, borderRadius: 3, marginRight: 3 }, legendText: { color: C.muted, fontSize: 6.2 },
  compactTableRow: { flexDirection: "row", alignItems: "center", minHeight: 17, borderBottomWidth: 1, borderBottomColor: "#E7EDF2" },
  compactLabel: { flex: 1, fontSize: 6.8 }, compactNumber: { width: 43, textAlign: "right", color: C.muted, fontSize: 6.5 },
  note: { backgroundColor: "#EAF2F8", borderLeftWidth: 3, borderLeftColor: C.cyan, padding: 6, color: C.muted, fontSize: 6.5, lineHeight: 1.35 },
  heatRow: { flexDirection: "row", minHeight: 13, borderBottomWidth: 1, borderBottomColor: "#E7EDF2", alignItems: "center" },
  heatName: { width: 83, fontSize: 6.2 }, heatCell: { flex: 1, textAlign: "center", paddingVertical: 3, fontSize: 6 },
  listItem: { flexDirection: "row", marginBottom: 4, lineHeight: 1.3 }, bullet: { width: 9, color: C.cyan, fontFamily: "Helvetica-Bold" },
});

function fmt(value: number | null | undefined, unit = "", digits = 1): string {
  if (value === null || value === undefined || !Number.isFinite(value)) return "Not available";
  const rendered = new Intl.NumberFormat("en-IE", { maximumFractionDigits: Number.isInteger(value) ? 0 : digits }).format(value);
  return `${rendered}${unit ? ` ${unit}` : ""}`;
}
function formatDate(value: string): string { const date = new Date(value.length === 10 ? `${value}T00:00:00Z` : value); return Number.isNaN(date.valueOf()) ? value : new Intl.DateTimeFormat("en-IE", { day: "numeric", month: "short", year: "numeric", timeZone: "UTC" }).format(date); }
function shortMonth(value: string): string { return value.trim().slice(0, 3).toUpperCase(); }
function sectionTitle(section: ReportSectionId): string { if (section === "season-pattern") return "Overview"; return section.replace(/-/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function metadata(model: ReportModel): ReportMetadata { return { version: model.reportVersion, sourceGeneratedAt: model.dataGeneratedAt, exportedAt: model.exportedAt }; }
function Header({ model, section }: { model: ReportModel; section: ReportSectionId }) { return <View style={styles.header}><View style={styles.headerBrand}>{model.brand.crestDataUri && <Image src={model.brand.crestDataUri} style={styles.headerCrest} />}<Text style={styles.eyebrow}>URC injury surveillance</Text></View><Text style={styles.headerLabel}>{sectionTitle(section)}</Text></View>; }
function Footer({ model, meta, cover = false }: { model: ReportModel; meta: ReportMetadata; cover?: boolean }) { return <View fixed style={[styles.footer, cover ? styles.coverFooter : {}]}><Text>{model.subjectName} | {model.season} | v{meta.version}</Text><Text>Source {formatDate(meta.sourceGeneratedAt)} | Exported {formatDate(meta.exportedAt)}</Text><Text render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`} /></View>; }
function PageShell({ model, meta, section, children }: { model: ReportModel; meta: ReportMetadata; section: ReportSectionId; children: ReactNode }) { return <Page size="A4" style={styles.page}><Header model={model} section={section} />{children}<Footer model={model} meta={meta} /></Page>; }
function PageTitle({ title, note }: { title: string; note: string }) { return <View><Text style={styles.title}>{title}</Text><Text style={styles.standfirst}>{note}</Text></View>; }
function Panel({ title, note, children, fill = false }: { title: string; note?: string; children: ReactNode; fill?: boolean }) { return <View style={[styles.panel, fill ? { height: "100%" } : {}]}><Text style={styles.panelTitle}>{title}</Text>{note && <Text style={styles.panelNote}>{note}</Text>}{children}</View>; }
function metricColour(key: string, index: number): string { if (/burden/i.test(key)) return C.coral; if (/incidence/i.test(key)) return /overall/i.test(key) ? C.cyan : C.amber; if (/severity/i.test(key)) return C.purple; if (/exposure|hour/i.test(key)) return C.mint; if (/time.loss/i.test(key)) return C.amber; return PALETTE[index % PALETTE.length]; }
function metricSeries(metric: ReportMetric, rows: readonly ReportPatternRow[]): Array<number | null> { if (/overall.incidence/i.test(metric.key)) return rows.map((r) => r.overallIncidencePer1000h); if (/incidence/i.test(metric.key)) return rows.map((r) => r.incidencePer1000h); if (/burden/i.test(metric.key)) return rows.map((r) => r.burdenPer1000h); if (/time.loss/i.test(metric.key)) return rows.map((r) => r.timeLossInjuries); if (/recorded/i.test(metric.key)) return rows.map((r) => r.recordedInjuries); return rows.map(() => null); }
function Sparkline({ values, colour }: { values: Array<number | null>; colour: string }) { const data = values.map((value, index) => ({ value, index })).filter((p): p is { value: number; index: number } => typeof p.value === "number" && Number.isFinite(p.value)); if (data.length < 2) return <View style={{ height: 18 }} />; const min = Math.min(...data.map((p) => p.value)), max = Math.max(...data.map((p) => p.value)), span = max - min || 1; const y = (v: number) => 20 - ((v - min) / span) * 16; const path = data.map((p, i) => `${i ? "L" : "M"} ${(p.index / Math.max(1, values.length - 1)) * 100} ${y(p.value)}`).join(" "); const last = data[data.length - 1]; return <Svg viewBox="0 0 100 22" style={{ height: 18, marginTop: 3 }}><Path d={path} stroke={colour} strokeWidth={2} fill="none" /><Circle cx={(last.index / Math.max(1, values.length - 1)) * 100} cy={y(last.value)} r={2.4} fill={colour} /></Svg>; }
function MetricCards({ model, dark = false, limit = 7 }: { model: ReportModel; dark?: boolean; limit?: number }) { const metrics = model.snapshotMetrics.slice(0, limit); return <View style={styles.metricGrid}>{metrics.map((metric, index) => { const colour = metricColour(metric.key, index); return <View key={metric.key} style={[styles.metricCell, { width: metrics.length > 4 ? "25%" : `${100 / metrics.length}%` }]}><View style={[styles.metricCard, dark ? { backgroundColor: C.navy2 } : {}, { borderTopWidth: 3, borderTopColor: colour }]}><Text style={[styles.metricValue, dark ? { color: C.white } : {}]}>{fmt(metric.value)}</Text><Text style={[styles.metricUnit, dark ? { color: "#AFC1D4" } : {}]}>{metric.unit}</Text><Text style={[styles.metricLabel, dark ? { color: C.white } : {}]}>{metric.label}</Text><Sparkline values={metricSeries(metric, model.monthlyInjuryPattern)} colour={colour} /></View></View>; })}</View>; }
function Legend({ items }: { items: Array<{ label: string; colour: string }> }) { return <View style={styles.legend}>{items.map((item) => <View key={item.label} style={styles.legendItem}><View style={[styles.legendDot, { backgroundColor: item.colour }]} /><Text style={styles.legendText}>{item.label}</Text></View>)}</View>; }

function TimelineChart({ rows }: { rows: readonly ReportPatternRow[] }) {
  const w = 500, h = 180, left = 28, right = 28, top = 14, bottom = 25, plotW = w - left - right, plotH = h - top - bottom;
  const maxCases = Math.max(1, ...rows.flatMap((r) => [r.recordedInjuries ?? 0, r.timeLossInjuries])); const maxRate = Math.max(1, ...rows.flatMap((r) => [r.overallIncidencePer1000h ?? 0, r.incidencePer1000h ?? 0]));
  const slot = plotW / Math.max(1, rows.length), x = (i: number) => left + slot * i + slot / 2, caseY = (v: number) => top + plotH - (v / maxCases) * plotH, rateY = (v: number) => top + plotH - (v / maxRate) * plotH;
  const linePath = (pick: (r: ReportPatternRow) => number | null) => rows.map((r, i) => pick(r) === null ? "" : `${i ? "L" : "M"} ${x(i)} ${rateY(pick(r) ?? 0)}`).filter(Boolean).join(" ");
  return <View><Svg viewBox={`0 0 ${w} ${h}`} style={{ height: 190 }}>{[0, .25, .5, .75, 1].map((tick) => <Line key={tick} x1={left} x2={w - right} y1={top + plotH * tick} y2={top + plotH * tick} stroke="#DCE5EC" />)}{rows.map((r, i) => { const centre = x(i), rw = Math.min(14, slot * .32); return <G key={r.month}><Rect x={centre - rw - 1} y={caseY(r.recordedInjuries ?? 0)} width={rw} height={top + plotH - caseY(r.recordedInjuries ?? 0)} rx={2} fill={C.cyan} opacity={.68} /><Rect x={centre + 1} y={caseY(r.timeLossInjuries)} width={rw} height={top + plotH - caseY(r.timeLossInjuries)} rx={2} fill={C.amber} /><SvgText x={centre} y={h - 8} textAnchor="middle" style={{ fontSize: 6, fill: C.muted }}>{shortMonth(r.month)}</SvgText></G>; })}<Path d={linePath((r) => r.overallIncidencePer1000h)} fill="none" stroke={C.cyan} strokeWidth={2.2} /><Path d={linePath((r) => r.incidencePer1000h)} fill="none" stroke={C.amber} strokeWidth={2.2} />{rows.map((r, i) => <G key={`d-${r.month}`}>{r.overallIncidencePer1000h !== null && <Circle cx={x(i)} cy={rateY(r.overallIncidencePer1000h)} r={2.2} fill={C.cyan} stroke={C.white} />}{r.incidencePer1000h !== null && <Circle cx={x(i)} cy={rateY(r.incidencePer1000h)} r={2.2} fill={C.amber} stroke={C.white} />}</G>)}<SvgText x={2} y={11} style={{ fontSize: 6, fill: C.muted }}>CASES</SvgText><SvgText x={w - 27} y={11} style={{ fontSize: 6, fill: C.muted }}>/1,000 H</SvgText></Svg><Legend items={[{ label: "Recorded injuries", colour: C.cyan }, { label: "TL injuries", colour: C.amber }, { label: "Overall incidence", colour: C.cyan }, { label: "TL incidence", colour: C.amber }]} /></View>;
}
function polar(cx: number, cy: number, radius: number, degrees: number) { const radians = degrees * Math.PI / 180; return { x: cx + radius * Math.cos(radians), y: cy + radius * Math.sin(radians) }; }
function arcPath(cx: number, cy: number, outer: number, inner: number, start: number, end: number) { const a = polar(cx, cy, outer, start), b = polar(cx, cy, outer, end), c = polar(cx, cy, inner, end), d = polar(cx, cy, inner, start); return `M ${a.x} ${a.y} A ${outer} ${outer} 0 0 1 ${b.x} ${b.y} L ${c.x} ${c.y} A ${inner} ${inner} 0 0 0 ${d.x} ${d.y} Z`; }
function HalfRing({ rows, colours, value = "recorded" }: { rows: readonly ReportDistributionRow[]; colours: Record<string, string>; value?: "recorded" | "timeLoss" }) { const scoped = rows.filter((r) => r.setting === "all").map((r) => ({ ...r, value: value === "recorded" ? r.recordedInjuries : r.timeLossInjuries })).filter((r) => r.value > 0); const total = scoped.reduce((sum, r) => sum + r.value, 0); let cursor = 180; return <View><Svg viewBox="0 0 220 105" style={{ height: 98 }}>{scoped.map((r, i) => { const span = total ? (r.value / total) * 180 : 0, start = cursor; cursor += span; return <Path key={r.key} d={arcPath(110, 100, 82, 53, start, cursor - 1)} fill={colours[r.key] ?? PALETTE[i % PALETTE.length]} />; })}<SvgText x={110} y={82} textAnchor="middle" style={{ fontSize: 22, fontWeight: "bold", fill: C.navy }}>{total}</SvgText><SvgText x={110} y={94} textAnchor="middle" style={{ fontSize: 6, fill: C.muted }}>TOTAL CASES</SvgText></Svg>{scoped.map((r, i) => <View key={r.key} style={[styles.compactTableRow, { minHeight: 14 }]}><View style={[styles.legendDot, { backgroundColor: colours[r.key] ?? PALETTE[i % PALETTE.length] }]} /><Text style={styles.compactLabel}>{r.label}</Text><Text style={styles.compactNumber}>{r.value} ({total ? Math.round(r.value / total * 100) : 0}%)</Text></View>)}</View>; }
function SettingBench({ rows }: { rows: readonly ReportSettingMetric[] }) { const colours: Record<string, string> = { match: C.cyan, training: C.mint }; return <View style={styles.split}>{rows.map((r) => <View style={styles.half} key={r.setting}><View style={[styles.darkPanel, { borderTopWidth: 4, borderTopColor: colours[r.setting] ?? C.blue }]}><Text style={{ color: C.white, fontFamily: "Helvetica-Bold", fontSize: 12 }}>{r.label}</Text><Text style={{ color: colours[r.setting], fontFamily: "Helvetica-Bold", fontSize: 20, marginTop: 5 }}>{r.timeLossInjuries}</Text><Text style={{ color: "#AFC1D4", fontSize: 6.5 }}>time-loss injuries</Text>{[["Recorded", r.recordedInjuries, ""], ["TL incidence", r.incidencePer1000h, "/1,000 h"], ["Burden", r.burdenPer1000h, "days/1,000 h"], ["Mean severity", r.meanSeverityDays, "days"], ["Exposure", r.exposureHours, "hours"]].map(([label, number, unit]) => <View key={String(label)} style={{ flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: "#294565", paddingTop: 4, marginTop: 4 }}><Text style={{ color: "#B6C7D8", fontSize: 6.5 }}>{label}</Text><Text style={{ color: C.white, fontFamily: "Helvetica-Bold", fontSize: 6.5 }}>{fmt(number as number | null, unit as string)}</Text></View>)}</View></View>)}</View>; }
function CompactSettingBench({ rows }: { rows: readonly ReportSettingMetric[] }) { const colours: Record<string, string> = { match: C.cyan, training: C.mint }; return <View>{rows.map((r) => <View key={r.setting} style={{ backgroundColor: C.navy, borderTopWidth: 4, borderTopColor: colours[r.setting], borderRadius: 4, padding: 8, marginBottom: 6 }}><View style={{ flexDirection: "row", alignItems: "baseline", justifyContent: "space-between" }}><Text style={{ color: C.white, fontFamily: "Helvetica-Bold", fontSize: 10 }}>{r.label}</Text><Text style={{ color: colours[r.setting], fontFamily: "Helvetica-Bold", fontSize: 16 }}>{r.timeLossInjuries} TL</Text></View>{[["Incidence", r.incidencePer1000h, "/1,000 h"], ["Burden", r.burdenPer1000h, "days/1,000 h"], ["Severity", r.meanSeverityDays, "days"]].map(([label, value, unit]) => <View key={String(label)} style={{ flexDirection: "row", justifyContent: "space-between", borderTopWidth: 1, borderTopColor: "#294565", paddingTop: 3, marginTop: 3 }}><Text style={{ color: "#B6C7D8", fontSize: 6 }}>{label}</Text><Text style={{ color: C.white, fontFamily: "Helvetica-Bold", fontSize: 6 }}>{fmt(value as number | null, unit as string)}</Text></View>)}</View>)}</View>; }
function profileColour(code: string) { let hash = 0; for (const char of code) hash = (hash * 31 + char.charCodeAt(0)) >>> 0; return PALETTE[hash % PALETTE.length]; }
function overall(rows: readonly ReportProfileRow[]) { return rows.filter((r) => r.setting === "all"); }
type ProfileMetric = "timeLossInjuries" | "incidencePer1000h" | "burdenPer1000h" | "meanSeverityDays";
function profileValue(row: ReportProfileRow, metric: ProfileMetric) { return row[metric] ?? 0; }
function RankedBars({ rows, metric = "timeLossInjuries", limit = 8, coloured = false }: { rows: readonly ReportProfileRow[]; metric?: ProfileMetric; limit?: number; coloured?: boolean }) { const ranked = [...rows].filter((r) => profileValue(r, metric) > 0).sort((a, b) => profileValue(b, metric) - profileValue(a, metric)).slice(0, limit), max = Math.max(1, ...ranked.map((r) => profileValue(r, metric))); return <View>{ranked.map((r, i) => <View key={r.code} style={{ flexDirection: "row", alignItems: "center", marginBottom: 5 }}><Text style={{ width: 17, color: C.muted, fontSize: 6.2 }}>{String(i + 1).padStart(2, "0")}</Text><Text style={{ width: 115, fontSize: 6.8 }}>{r.label}</Text><View style={{ flex: 1, height: 7, backgroundColor: "#E8EEF3", borderRadius: 3, overflow: "hidden" }}><View style={{ height: 7, width: `${profileValue(r, metric) / max * 100}%`, backgroundColor: coloured ? profileColour(r.code) : C.cyan }} /></View><Text style={{ width: 48, textAlign: "right", color: C.muted, fontFamily: "Helvetica-Bold", fontSize: 6.5 }}>{fmt(profileValue(r, metric))}</Text></View>)}</View>; }

const BODY_PATHS: Array<{ code: string; d?: string; circle?: [number, number, number]; rect?: [number, number, number, number, number] }> = [
  { code: "head", circle: [60,25,20] }, { code: "neck", rect: [51,45,18,17,6] }, { code: "shoulder", d: "M24 70 Q42 57 60 58 Q78 57 96 70 L91 88 Q75 78 60 79 Q45 78 29 88 Z" }, { code: "upper_arm", d: "M25 74 Q17 80 15 111 L24 145 L38 141 L36 91 Z M95 74 Q103 80 105 111 L96 145 L82 141 L84 91 Z" }, { code: "elbow", d: "M17 143 Q26 136 35 143 L34 158 Q26 164 18 157 Z M85 143 Q94 136 103 143 L102 158 Q94 164 86 157 Z" }, { code: "forearm", d: "M18 157 L34 157 L31 205 L19 205 Z M86 157 L102 157 L101 205 L89 205 Z" }, { code: "wrist", d: "M19 204 H31 V214 H19 Z M89 204 H101 V214 H89 Z" }, { code: "hand", d: "M17 213 Q25 208 33 214 L30 239 Q25 248 20 239 Z M87 214 Q95 208 103 213 L100 239 Q95 248 90 239 Z" }, { code: "chest", d: "M36 76 Q60 69 84 76 L82 124 Q60 133 38 124 Z" }, { code: "abdomen", d: "M39 125 Q60 133 81 125 L78 175 Q60 184 42 175 Z" }, { code: "hip_groin", d: "M42 175 Q60 183 78 175 L84 201 L66 214 L60 200 L54 214 L36 201 Z" }, { code: "thigh", d: "M37 199 L57 207 L54 280 L33 280 Z M63 207 L83 199 L87 280 L66 280 Z" }, { code: "knee", d: "M33 278 H55 L56 300 H34 Z M65 300 L66 278 H87 L86 300 Z" }, { code: "lower_leg", d: "M34 299 H56 L52 365 H37 Z M64 299 H86 L83 365 H68 Z" }, { code: "ankle", d: "M37 362 H52 L51 376 H37 Z M68 362 H83 V376 H69 Z" }, { code: "foot", d: "M37 374 H51 L48 389 H25 Q22 383 30 379 Z M69 374 H83 L90 379 Q98 383 95 389 H72 Z" },
];
const BACK_PATHS = BODY_PATHS.filter((shape) => shape.code !== "chest" && shape.code !== "abdomen").concat([
  { code: "thoracic_spine", d: "M38 76 Q60 69 82 76 L80 130 Q60 139 40 130 Z M56 78 H64 V132 H56 Z" },
  { code: "lumbosacral", d: "M40 131 Q60 139 80 131 L77 176 Q60 186 43 176 Z M54 145 H66 V178 H54 Z" },
]);
function bodyHeat(value: number, max: number) { if (value <= 0) return "#D7E2EA"; const ratio = Math.min(1, value / Math.max(1, max)); return ratio > .72 ? "#D93F45" : ratio > .38 ? C.orange : C.amber; }
function BodyMapPdf({ rows }: { rows: readonly ReportProfileRow[] }) { const byCode = new Map(rows.map((r) => [r.code, r])), max = Math.max(1, ...rows.map((r) => r.timeLossInjuries)); const figure = (shapes: typeof BODY_PATHS, offset: number, label: string) => <G transform={`translate(${offset} 12)`}><SvgText x={60} y={-2} textAnchor="middle" style={{ fontSize: 9, fill: C.muted }}>{label}</SvgText>{shapes.map((shape) => { const props = { fill: bodyHeat(byCode.get(shape.code)?.timeLossInjuries ?? 0, max), stroke: C.white, strokeWidth: 1 }; if (shape.circle) return <Circle key={`${label}-${shape.code}`} cx={shape.circle[0]} cy={shape.circle[1]} r={shape.circle[2]} {...props} />; if (shape.rect) return <Rect key={`${label}-${shape.code}`} x={shape.rect[0]} y={shape.rect[1]} width={shape.rect[2]} height={shape.rect[3]} rx={shape.rect[4]} {...props} />; return <Path key={`${label}-${shape.code}`} d={shape.d ?? ""} {...props} />; })}</G>; return <View><Svg viewBox="0 0 270 420" style={{ height: 250 }}>{figure(BODY_PATHS, 5, "Front")}{figure(BACK_PATHS, 140, "Back")}</Svg><Legend items={[{ label: "Lower", colour: C.amber }, { label: "Mid", colour: C.orange }, { label: "Higher", colour: "#D93F45" }]} /></View>; }
function MirroredBars({ rows, limit = 9, rowGap = 6 }: { rows: readonly ReportProfileRow[]; limit?: number; rowGap?: number }) { const allRows = overall(rows).sort((a,b) => b.timeLossInjuries - a.timeLossInjuries).slice(0,limit), byKey = new Map(rows.map((r) => [`${r.setting}:${r.code}`, r])), max = Math.max(1, ...allRows.flatMap((r) => [byKey.get(`match:${r.code}`)?.timeLossInjuries ?? 0, byKey.get(`training:${r.code}`)?.timeLossInjuries ?? 0])); return <View>{allRows.map((r) => { const match = byKey.get(`match:${r.code}`)?.timeLossInjuries ?? 0, training = byKey.get(`training:${r.code}`)?.timeLossInjuries ?? 0; return <View key={r.code} style={{ flexDirection: "row", alignItems: "center", marginBottom: rowGap }}><Text style={{ width: 20, textAlign: "right", color: C.muted, fontSize: 6 }}>{match}</Text><View style={{ flex: 1, height: 7, alignItems: "flex-end", backgroundColor: "#E8EEF3" }}><View style={{ width: `${match / max * 100}%`, height: 7, backgroundColor: C.cyan }} /></View><Text style={{ width: 125, textAlign: "center", fontSize: 6.5 }}>{r.label}</Text><View style={{ flex: 1, height: 7, backgroundColor: "#E8EEF3" }}><View style={{ width: `${training / max * 100}%`, height: 7, backgroundColor: C.mint }} /></View><Text style={{ width: 20, color: C.muted, fontSize: 6 }}>{training}</Text></View>; })}<Legend items={[{ label: "Match TL injuries", colour: C.cyan }, { label: "Training TL injuries", colour: C.mint }]} /></View>; }
function CommonLanes({ rows, cardHeight = 40 }: { rows: readonly ReportProfileRow[]; cardHeight?: number }) { const defs: Array<{ metric: ProfileMetric; label: string; unit: string }> = [{ metric: "timeLossInjuries", label: "Frequency", unit: "cases" }, { metric: "incidencePer1000h", label: "Incidence", unit: "/1,000 h" }, { metric: "burdenPer1000h", label: "Burden", unit: "days/1,000 h" }, { metric: "meanSeverityDays", label: "Severity", unit: "mean days" }]; return <View style={{ flexDirection: "row", marginHorizontal: -3 }}>{defs.map((d) => { const ranked = [...rows].filter((r) => profileValue(r,d.metric) > 0).sort((a,b) => profileValue(b,d.metric)-profileValue(a,d.metric)).slice(0,5); return <View key={d.metric} style={{ width: "25%", paddingHorizontal: 3 }}><Text style={[styles.panelTitle,{marginBottom:5}]}>{d.label}</Text>{ranked.map((r,i) => <View key={r.code} style={{ backgroundColor: profileColour(r.code), borderRadius: 3, padding: 5, minHeight: cardHeight, marginBottom: 4, color: C.white }}><Text style={{ fontFamily: "Helvetica-Bold", fontSize: 6.8, lineHeight: 1.15 }}>{i+1}. {r.label}</Text><Text style={{ fontFamily: "Helvetica-Bold", fontSize: 12, marginTop: 4 }}>{fmt(profileValue(r,d.metric))}</Text><Text style={{ fontSize: 5.5 }}>{d.unit}</Text></View>)}</View>; })}</View>; }
function impactRows(rows: readonly ReportProfileRow[]) { return overall(rows).filter((r) => (r.incidencePer1000h ?? 0) > 0 && (r.meanSeverityDays ?? 0) > 0).sort((a,b) => b.timeLossInjuries-a.timeLossInjuries || (b.burdenPer1000h ?? 0)-(a.burdenPer1000h ?? 0)); }
function ImpactMatrix({ rows, chartHeight = 150 }: { rows: readonly ReportProfileRow[]; chartHeight?: number }) { const data = impactRows(rows), w=310,h=125,left=25,top=7,right=8,bottom=18,plotW=w-left-right,plotH=h-top-bottom,maxX=Math.max(1,...data.map((r)=>r.incidencePer1000h??0))*1.1,maxY=Math.max(2,...data.map((r)=>r.meanSeverityDays??0)),maxLog=Math.log10(maxY*1.15),px=(v:number)=>left+v/maxX*plotW,py=(v:number)=>top+plotH-(Math.log10(Math.max(1,v))/Math.max(.1,maxLog))*plotH; return <View style={styles.split}><View style={{width:"62%",paddingRight:4}}><Svg viewBox={`0 0 ${w} ${h}`} style={{height:chartHeight}}><Rect x={left} y={top} width={plotW/3} height={plotH} fill="#DDF3E8"/><Rect x={left+plotW/3} y={top} width={plotW/3} height={plotH} fill="#FFF0C8"/><Rect x={left+plotW*2/3} y={top} width={plotW/3} height={plotH} fill="#F9D7DC"/>{data.map((r,i)=><G key={r.code}><Circle cx={px(r.incidencePer1000h??0)} cy={py(r.meanSeverityDays??1)} r={6} fill={profileColour(r.code)} stroke={C.white} strokeWidth={1.2}/><SvgText x={px(r.incidencePer1000h??0)} y={py(r.meanSeverityDays??1)+2} textAnchor="middle" fontSize={5.5} fontWeight="bold" fill={C.white}>{i+1}</SvgText></G>)}<SvgText x={left+plotW/2} y={h-4} textAnchor="middle" fontSize={6} fill={C.muted}>TL INCIDENCE /1,000 H</SvgText><SvgText x={3} y={top+plotH/2} fontSize={6} fill={C.muted}>SEVERITY</SvgText></Svg></View><View style={{width:"38%",paddingLeft:4}}>{data.slice(0,12).map((r,i)=><View key={r.code} style={{flexDirection:"row",alignItems:"center",marginBottom:3}}><View style={{width:11,height:11,borderRadius:6,backgroundColor:profileColour(r.code),alignItems:"center",justifyContent:"center",marginRight:4}}><Text style={{color:C.white,fontFamily:"Helvetica-Bold",fontSize:5.5}}>{i+1}</Text></View><Text style={{flex:1,fontSize:5.8}}>{r.label}</Text><Text style={{width:35,textAlign:"right",color:C.muted,fontSize:5.5}}>{fmt(r.burdenPer1000h)}</Text></View>)}<Text style={{color:C.muted,fontSize:5.3}}>Key value: burden, days per 1,000 h.</Text></View></View>; }

function FamilyRanking({ rows }: { rows: readonly ReportInjuryTypeFamily[] }) { const ranked=rows.filter((r)=>r.setting==="all"&&r.timeLossInjuries>0).sort((a,b)=>b.timeLossInjuries-a.timeLossInjuries),max=Math.max(1,...ranked.map((r)=>r.timeLossInjuries)); return <View>{ranked.map((r,i)=><View key={r.code} style={{marginBottom:6}}><View style={{flexDirection:"row",justifyContent:"space-between"}}><Text style={{fontSize:6.8}}>{i+1}. {r.label}</Text><Text style={{color:C.muted,fontFamily:"Helvetica-Bold",fontSize:6.5}}>{r.timeLossInjuries} TL | {fmt(r.incidencePer1000h)} /1,000 h</Text></View><View style={{height:7,backgroundColor:"#E8EEF3",marginTop:2}}><View style={{height:7,width:`${r.timeLossInjuries/max*100}%`,backgroundColor:profileColour(r.code)}}/></View></View>)}</View>; }
function FamilyDossier({ rows }: { rows: readonly ReportInjuryTypeFamily[] }) { const lead=rows.filter((r)=>r.setting==="all").sort((a,b)=>b.timeLossInjuries-a.timeLossInjuries)[0]; if(!lead)return <Text style={styles.panelNote}>Not available</Text>; return <View><View style={[styles.darkPanel,{borderTopWidth:4,borderTopColor:profileColour(lead.code)}]}><Text style={{color:C.cyan,fontSize:6.5,letterSpacing:1,fontFamily:"Helvetica-Bold"}}>LEADING FAMILY</Text><Text style={{color:C.white,fontFamily:"Helvetica-Bold",fontSize:16,marginTop:4}}>{lead.label}</Text><View style={{flexDirection:"row",marginTop:8}}>{[["TL injuries",lead.timeLossInjuries],["Incidence",lead.incidencePer1000h],["Burden",lead.burdenPer1000h],["Mean days",lead.meanSeverityDays]].map(([label,value])=><View key={String(label)} style={{width:"25%"}}><Text style={{color:C.white,fontFamily:"Helvetica-Bold",fontSize:11}}>{fmt(value as number|null)}</Text><Text style={{color:"#AFC1D4",fontSize:5.5}}>{label}</Text></View>)}</View></View><Text style={[styles.panelTitle,{marginTop:8}]}>Subtype detail</Text>{lead.subtypes.filter((r)=>r.timeLossInjuries>0).map((r)=><View key={r.code} style={styles.compactTableRow}><Text style={styles.compactLabel}>{r.label}</Text><Text style={styles.compactNumber}>{r.timeLossInjuries} TL</Text><Text style={styles.compactNumber}>{fmt(r.daysLost)} days</Text></View>)}</View>; }
type ComparisonKey="matchIncidencePer1000h"|"matchBurdenPer1000h"|"trainingIncidencePer1000h"|"trainingBurdenPer1000h";
const heatColumns:Array<{key:ComparisonKey;label:string}>=[{key:"matchIncidencePer1000h",label:"Match inc."},{key:"matchBurdenPer1000h",label:"Match burden"},{key:"trainingIncidencePer1000h",label:"Training inc."},{key:"trainingBurdenPer1000h",label:"Training burden"}];
function benchmarkColour(value:number|null,mean:number|null){if(value===null||mean===null||mean<=0)return"#E8EEF3";if(value<=mean*.9)return C.green;if(value>=mean*1.1)return C.red;return"#D9A437";}
function safeComparisonRows(model: ReportModel) { let anonymous = 0; return model.comparisonHeatmap.map((row) => ({ ...row, label: row.isSubject ? model.subjectName : `Anonymous club ${String(++anonymous).padStart(2, "0")}` })); }
function Heatmap({model,rowHeight=13}:{model:ReportModel;rowHeight?:number}){return <View><View style={[styles.heatRow,{minHeight:rowHeight}]}><Text style={styles.heatName}>Club</Text>{heatColumns.map((c)=><Text key={c.key} style={styles.heatCell}>{c.label}</Text>)}</View>{safeComparisonRows(model).map((r,i)=><View key={`${r.label}-${i}`} style={[styles.heatRow,{minHeight:rowHeight}]}><Text style={[styles.heatName,r.isSubject?{fontFamily:"Helvetica-Bold",color:model.brand.accentColour}:{}]}>{r.label}</Text>{heatColumns.map((c)=>{const colour=benchmarkColour(r[c.key],model.comparisonBenchmarks[c.key]);return <Text key={c.key} style={[styles.heatCell,{backgroundColor:colour,color:colour==="#E8EEF3"||colour==="#D9A437"?C.ink:C.white}]}>{fmt(r[c.key])}</Text>;})}</View>)}</View>;}
function ComparisonLadder({model,rowGap=4}:{model:ReportModel;rowGap?:number}){const rows=safeComparisonRows(model).filter((r)=>r.allIncidencePer1000h!==null).sort((a,b)=>(b.allIncidencePer1000h??0)-(a.allIncidencePer1000h??0)),max=Math.max(1,...rows.map((r)=>r.allIncidencePer1000h??0)),mean=model.comparisonBenchmarks.allIncidencePer1000h??0;return <View>{rows.map((r,i)=><View key={`${r.label}-${i}`} style={{flexDirection:"row",alignItems:"center",marginBottom:rowGap}}><Text style={{width:18,color:C.muted,fontSize:6}}>{i+1}</Text><Text style={{width:83,fontFamily:r.isSubject?"Helvetica-Bold":"Helvetica",color:r.isSubject?model.brand.accentColour:C.ink,fontSize:6.3}}>{r.label}</Text><View style={{flex:1,height:7,backgroundColor:"#E8EEF3",position:"relative"}}><View style={{height:7,width:`${(r.allIncidencePer1000h??0)/max*100}%`,backgroundColor:r.isSubject?model.brand.accentColour:C.blue}}/><View style={{position:"absolute",left:`${mean/max*100}%`,top:-2,width:1,height:11,backgroundColor:C.coral}}/></View><Text style={{width:35,textAlign:"right",fontSize:6.3}}>{fmt(r.allIncidencePer1000h)}</Text></View>)}</View>;}
function ComparisonScatter({model,chartHeight=180}:{model:ReportModel;chartHeight?:number}){const data=safeComparisonRows(model).filter((r)=>r.matchIncidencePer1000h!==null&&r.trainingIncidencePer1000h!==null),w=500,h=180,left=30,top=10,right=10,bottom=22,plotW=w-left-right,plotH=h-top-bottom,maxX=Math.max(1,...data.map((r)=>r.matchIncidencePer1000h??0))*1.08,maxY=Math.max(1,...data.map((r)=>r.trainingIncidencePer1000h??0))*1.08,px=(v:number)=>left+v/maxX*plotW,py=(v:number)=>top+plotH-v/maxY*plotH,meanX=model.comparisonBenchmarks.matchIncidencePer1000h??0,meanY=model.comparisonBenchmarks.trainingIncidencePer1000h??0,maxExposure=Math.max(1,...data.map((r)=>r.exposureHours??0));return <Svg viewBox={`0 0 ${w} ${h}`} style={{height:chartHeight}}><Rect x={left} y={top} width={plotW} height={plotH} fill="#F4F8FB"/><Line x1={px(meanX)} x2={px(meanX)} y1={top} y2={top+plotH} stroke={C.coral} strokeDasharray="4 3"/><Line x1={left} x2={left+plotW} y1={py(meanY)} y2={py(meanY)} stroke={C.coral} strokeDasharray="4 3"/>{data.map((r,i)=>{const radius=3+Math.sqrt((r.exposureHours??0)/maxExposure)*5;return <G key={`${r.label}-${i}`}><Circle cx={px(r.matchIncidencePer1000h??0)} cy={py(r.trainingIncidencePer1000h??0)} r={radius} fill={r.isSubject?model.brand.accentColour:C.blue} opacity={r.isSubject?1:.55} stroke={C.white}/>{r.isSubject&&<SvgText x={px(r.matchIncidencePer1000h??0)+9} y={py(r.trainingIncidencePer1000h??0)-3} fontSize={7} fontWeight="bold" fill={model.brand.accentColour}>{model.subjectName}</SvgText>}</G>;})}<SvgText x={left+plotW/2} y={h-4} textAnchor="middle" fontSize={6} fill={C.muted}>MATCH TL INCIDENCE /1,000 H</SvgText><SvgText x={3} y={top+plotH/2} fontSize={6} fill={C.muted}>TRAINING</SvgText></Svg>;}
function ExposureTrend({model,chartHeight=170}:{model:ReportModel;chartHeight?:number}){const rows=model.exposure.monthly,w=500,h=165,left=26,top=10,right=25,bottom=20,plotW=w-left-right,plotH=h-top-bottom,maxHours=Math.max(1,...rows.map((r)=>r.exposureHours??0)),maxDistance=Math.max(1,...rows.map((r)=>r.distanceKm??0)),slot=plotW/Math.max(1,rows.length),x=(i:number)=>left+slot*i+slot/2,hoursY=(v:number)=>top+plotH-v/maxHours*plotH,distY=(v:number)=>top+plotH-v/maxDistance*plotH,distancePath=rows.map((r,i)=>r.distanceKm===null?"":`${i?"L":"M"} ${x(i)} ${distY(r.distanceKm)}`).filter(Boolean).join(" ");return <View><Svg viewBox={`0 0 ${w} ${h}`} style={{height:chartHeight}}>{[0,.5,1].map((tick)=><Line key={tick} x1={left} x2={w-right} y1={top+plotH*tick} y2={top+plotH*tick} stroke="#DCE5EC"/>)}{rows.map((r,i)=><G key={r.month}><Rect x={x(i)-Math.min(14,slot*.3)} y={hoursY(r.exposureHours??0)} width={Math.min(28,slot*.6)} height={top+plotH-hoursY(r.exposureHours??0)} rx={2} fill={C.mint}/><SvgText x={x(i)} y={h-6} textAnchor="middle" fontSize={6} fill={C.muted}>{shortMonth(r.month)}</SvgText></G>)}<Path d={distancePath} fill="none" stroke={C.cyan} strokeWidth={2.3}/>{rows.map((r,i)=>r.distanceKm!==null&&<Circle key={r.month} cx={x(i)} cy={distY(r.distanceKm)} r={2.2} fill={C.cyan}/>)}</Svg><Legend items={[{label:"Player-hours",colour:C.mint},{label:"Distance (km)",colour:C.cyan}]}/></View>;}
function ExposureLadder({model,keyName,label,colour,rowGap=4}:{model:ReportModel;keyName:"exposureHours"|"distanceKm";label:string;colour:string;rowGap?:number}){const rows=safeComparisonRows(model).filter((r)=>r[keyName]!==null).sort((a,b)=>(b[keyName]??0)-(a[keyName]??0)),max=Math.max(1,...rows.map((r)=>r[keyName]??0));return <View><Text style={styles.panelTitle}>{label}</Text>{rows.map((r,i)=><View key={`${r.label}-${i}`} style={{flexDirection:"row",alignItems:"center",marginBottom:rowGap}}><Text style={{width:15,color:C.muted,fontSize:5.8}}>{i+1}</Text><Text style={{width:76,color:r.isSubject?model.brand.accentColour:C.ink,fontFamily:r.isSubject?"Helvetica-Bold":"Helvetica",fontSize:5.9}}>{r.label}</Text><View style={{flex:1,height:6,backgroundColor:"#E8EEF3"}}><View style={{height:6,width:`${(r[keyName]??0)/max*100}%`,backgroundColor:r.isSubject?model.brand.accentColour:colour}}/></View><Text style={{width:36,textAlign:"right",fontSize:5.8}}>{fmt(r[keyName],"",0)}</Text></View>)}</View>;}
function ComparisonTable({metrics,limit=6}:{metrics:readonly SeasonComparisonMetric[];limit?:number}){return <View><View style={[styles.compactTableRow,{borderBottomColor:C.navy}]}><Text style={styles.compactLabel}>Metric</Text><Text style={styles.compactNumber}>Current</Text><Text style={styles.compactNumber}>Prior</Text><Text style={[styles.compactNumber,{width:80}]}>Change</Text></View>{metrics.slice(0,limit).map((m)=><View key={m.key} style={[styles.compactTableRow,{minHeight:22}]}><Text style={styles.compactLabel}>{m.label}</Text><Text style={[styles.compactNumber,{color:C.navy,fontFamily:"Helvetica-Bold"}]}>{fmt(m.currentValue)}</Text><Text style={styles.compactNumber}>{fmt(m.priorValue)}</Text><Text style={[styles.compactNumber,{width:80}]}>{m.deltaReason??fmt(m.delta)}</Text></View>)}</View>;}

function CoverPage({model,meta}:{model:ReportModel;meta:ReportMetadata}){return <Page size="A4" style={styles.cover}><View style={{height:38,flexDirection:"row",justifyContent:"space-between",alignItems:"center"}}><Text style={styles.eyebrow}>United Rugby Championship</Text><Text style={{color:"#AFC1D4",fontSize:7}}>REPORT V{meta.version}</Text></View><View style={{position:"absolute",right:-60,top:145,width:300,height:300,borderRadius:150,borderWidth:34,borderColor:"#0C315D",opacity:.65}}/><View style={{position:"absolute",right:10,top:215,width:180,height:180,borderRadius:90,borderWidth:2,borderColor:C.cyan,opacity:.28}}/><View style={{flex:1,justifyContent:"center"}}><View style={{flexDirection:"row",alignItems:"center"}}><View style={{width:"68%"}}><Text style={{color:C.cyan,fontFamily:"Helvetica-Bold",fontSize:9,letterSpacing:1.5}}>TEAM PERFORMANCE REPORT</Text><Text style={{color:C.white,fontFamily:"Helvetica-Bold",fontSize:38,lineHeight:1.02,marginTop:14}}>{model.subjectName}</Text><Text style={{color:C.white,fontFamily:"Helvetica-Bold",fontSize:28,lineHeight:1.04}}>Injury surveillance</Text><Text style={{color:C.blue,fontFamily:"Helvetica-Bold",fontSize:17,marginTop:13}}>{model.season} season</Text></View><View style={{width:"32%",alignItems:"center"}}>{model.brand.crestDataUri&&<Image src={model.brand.crestDataUri} style={{width:122,height:122,objectFit:"contain"}}/>}</View></View><View style={{height:1,backgroundColor:"#294565",marginTop:32,marginBottom:18}}/><View style={{flexDirection:"row"}}><View style={{width:"50%"}}><Text style={{color:"#8199B3",fontSize:6.5,letterSpacing:1}}>ANALYSIS WINDOW</Text><Text style={{color:C.white,fontSize:10,marginTop:5}}>{formatDate(model.analysisWindow.start)} to {formatDate(model.analysisWindow.end)}</Text></View><View style={{width:"25%"}}><Text style={{color:"#8199B3",fontSize:6.5,letterSpacing:1}}>REPORT VERSION</Text><Text style={{color:C.white,fontSize:10,marginTop:5}}>v{meta.version}</Text></View><View style={{width:"25%"}}><Text style={{color:"#8199B3",fontSize:6.5,letterSpacing:1}}>EXPORTED</Text><Text style={{color:C.white,fontSize:10,marginTop:5}}>{formatDate(meta.exportedAt)}</Text></View></View></View><Footer model={model} meta={meta} cover/></Page>;}
function SeasonPattern({model,meta}:{model:ReportModel;meta:ReportMetadata}){return <PageShell model={model} meta={meta} section="season-pattern"><PageTitle title="Season overview" note="Headline measures, the monthly pattern and setting split are brought together on the first analytical page."/><MetricCards model={model}/><View style={{marginTop:8}}><Panel title="Monthly injury pattern" note="Recorded and time-loss cases use the left axis. Overall and TL incidence use the right axis."><TimelineChart rows={model.monthlyInjuryPattern}/></Panel></View><View style={{marginTop:8}}><Panel title="Match and training" note="Released setting measures shown side by side."><SettingBench rows={model.matchTraining}/></Panel></View></PageShell>;}
function SeverityContact({model,meta}:{model:ReportModel;meta:ReportMetadata}){return <PageShell model={model} meta={meta} section="severity-contact"><PageTitle title="Severity and mechanism" note="Case consequences and contact context are shown alongside the team setting split."/><View style={[styles.split,{height:300}]}><View style={styles.third}><Panel fill title="Severity profile" note="All recorded injuries by released duration band."><HalfRing rows={model.severityDistribution} colours={SEVERITY_COLOURS}/></Panel></View><View style={styles.third}><Panel fill title="Contact mechanism" note="Time-loss injuries by released mechanism."><HalfRing rows={model.contactDistribution} colours={CONTACT_COLOURS} value="timeLoss"/></Panel></View><View style={styles.third}><Panel fill title="Setting contrast" note="Match and training metrics in context."><CompactSettingBench rows={model.matchTraining}/></Panel></View></View><View style={{marginTop:8}}><Panel title="Leading locations and injury types" note="Colour-coded time-loss rankings from the released profile rows."><View style={styles.split}><View style={styles.half}><RankedBars rows={overall(model.injuryProfile.bodyLocations)} limit={8} coloured/></View><View style={styles.half}><RankedBars rows={overall(model.injuryProfile.injuryTypes)} limit={8} coloured/></View></View></Panel></View></PageShell>;}
function InjuryLocation({model,meta}:{model:ReportModel;meta:ReportMetadata}){const rows=overall(model.injuryProfile.bodyLocations);return <PageShell model={model} meta={meta} section="injury-location"><PageTitle title="Injury location" note="The body map, ranked locations and match-training split use the released body-location rows."/><View style={[styles.split,{height:360}]}><View style={{width:"34%",paddingHorizontal:4}}><Panel fill title="Body heat map" note="Colour is based on time-loss case count."><BodyMapPdf rows={rows}/></Panel></View><View style={{width:"66%",paddingHorizontal:4}}><Panel fill title="Ranked locations" note="Time-loss injuries, incidence, burden and severity."><RankedBars rows={rows} limit={12} coloured/>{[...rows].sort((a,b)=>b.timeLossInjuries-a.timeLossInjuries).slice(0,8).map((r)=><View key={r.code} style={styles.compactTableRow}><Text style={styles.compactLabel}>{r.label}</Text><Text style={styles.compactNumber}>{fmt(r.incidencePer1000h)} inc.</Text><Text style={styles.compactNumber}>{fmt(r.burdenPer1000h)} burden</Text><Text style={styles.compactNumber}>{fmt(r.meanSeverityDays)} days</Text></View>)}</Panel></View></View><View style={{marginTop:8,height:260}}><Panel fill title="Match versus training by region" note="Time-loss case counts on a shared scale."><MirroredBars rows={model.injuryProfile.bodyLocations} rowGap={9}/></Panel></View></PageShell>;}
function CommonInjuries({model,meta}:{model:ReportModel;meta:ReportMetadata}){const diagnoses=overall(model.injuryProfile.diagnoses);return <PageShell model={model} meta={meta} section="common-injuries"><PageTitle title="Common injuries" note="Each diagnosis keeps one colour across frequency, incidence, burden and severity."/><View style={{height:350}}><Panel fill title="Four views of the leading diagnoses" note="Top five released diagnoses for each measure."><CommonLanes rows={diagnoses} cardHeight={49}/></Panel></View><View style={{marginTop:8,height:320}}><Panel fill title="Diagnosis impact matrix" note="Position combines TL incidence and mean severity. The numbered key reports burden."><View style={{flex:1,justifyContent:"center"}}><ImpactMatrix rows={model.injuryProfile.diagnoses} chartHeight={250}/></View></Panel></View></PageShell>;}
function ImpactMatrices({model,meta}:{model:ReportModel;meta:ReportMetadata}){return <PageShell model={model} meta={meta} section="impact-matrices"><PageTitle title="Injury impact matrices" note="Location and injury-type views use the same axes and visual grammar as diagnosis."/><View style={{height:330}}><Panel fill title="Location impact" note="TL incidence against logarithmic mean severity."><View style={{flex:1,justifyContent:"center"}}><ImpactMatrix rows={model.injuryProfile.bodyLocations} chartHeight={275}/></View></Panel></View><View style={{marginTop:8,height:330}}><Panel fill title="Injury-type impact" note="TL incidence against logarithmic mean severity."><View style={{flex:1,justifyContent:"center"}}><ImpactMatrix rows={model.injuryProfile.injuryTypes} chartHeight={275}/></View></Panel></View></PageShell>;}
function InjuryTypes({model,meta}:{model:ReportModel;meta:ReportMetadata}){return <PageShell model={model} meta={meta} section="injury-types"><PageTitle title="Injury type" note="Injury families, subtype detail and setting contrast share one analytical page."/><View style={[styles.split,{height:300}]}><View style={styles.half}><Panel fill title="Injury-family ranking" note="Overall time-loss injuries and incidence."><FamilyRanking rows={model.injuryProfile.injuryTypeFamilies}/></Panel></View><View style={styles.half}><Panel fill title="Leading-family dossier" note="Released family and subtype measures."><FamilyDossier rows={model.injuryProfile.injuryTypeFamilies}/></Panel></View></View><View style={{marginTop:8,height:285}}><Panel fill title="Match versus training by injury type" note="Time-loss case counts on a shared scale."><MirroredBars rows={model.injuryProfile.injuryTypes} limit={10} rowGap={9}/></Panel></View></PageShell>;}
function Exposure({model,meta}:{model:ReportModel;meta:ReportMetadata}){const cards:Array<ReportMetric>=[{key:"total-hours",label:"Total exposure",value:model.exposure.totalHours,unit:"player-hours",formula:"released exposure"},{key:"match-hours",label:"Match exposure",value:model.exposure.matchHours,unit:"player-hours",formula:"released exposure"},{key:"training-hours",label:"Training exposure",value:model.exposure.trainingHours,unit:"player-hours",formula:"released exposure"},{key:"distance",label:"Distance",value:model.exposure.totalDistanceKm,unit:"km",formula:"released distance"}],pseudo={...model,snapshotMetrics:cards};return <PageShell model={model} meta={meta} section="exposure"><PageTitle title="Exposure" note="The released denominator is shown over time and against the anonymous league cohort."/><MetricCards model={pseudo} limit={4}/><View style={{marginTop:8,height:255}}><Panel fill title="Monthly exposure and distance" note="Bars show player-hours. The line shows kilometres."><ExposureTrend model={model} chartHeight={205}/></Panel></View><View style={[styles.split,{marginTop:8,height:330}]}><View style={styles.half}><Panel fill title="Club exposure hours"><View style={{flex:1,justifyContent:"center"}}><ExposureLadder model={model} keyName="exposureHours" label="Player-hours" colour={C.mint} rowGap={7}/></View></Panel></View><View style={styles.half}><Panel fill title="Club distance"><View style={{flex:1,justifyContent:"center"}}><ExposureLadder model={model} keyName="distanceKm" label="Kilometres" colour={C.cyan} rowGap={7}/></View></Panel></View></View></PageShell>;}
function TeamComparison({model,meta}:{model:ReportModel;meta:ReportMetadata}){return <PageShell model={model} meta={meta} section="team-comparison"><PageTitle title="Team comparison" note={`Other clubs remain anonymous. ${model.subjectName} is highlighted against released league benchmarks.`}/><View style={[styles.split,{height:285}]}><View style={styles.half}><Panel fill title="Overall TL incidence ladder" note="The coral marker is the league mean."><ComparisonLadder model={model} rowGap={7}/></Panel></View><View style={styles.half}><Panel fill title="Match versus training TL incidence" note="Bubble area reflects exposure hours."><ComparisonScatter model={model} chartHeight={225}/></Panel></View></View><View style={{marginTop:8,height:375}}><Panel fill title="Four-metric benchmark heat map" note="Green is at least 10% below the mean, amber is within 10%, red is at least 10% above."><View style={{flex:1,justifyContent:"center"}}><Heatmap model={model} rowHeight={18}/></View></Panel></View></PageShell>;}
function SeasonMethodology({model,meta}:{model:ReportModel;meta:ReportMetadata}){const items=[...model.method,...model.limitations];return <PageShell model={model} meta={meta} section="season-methodology"><PageTitle title="Season comparison and method" note={`Current released values are compared with the approved ${model.seasonComparison.priorSeason} release where definitions permit.`}/><View style={[styles.split,{height:285}]}><View style={{width:"58%",paddingHorizontal:4}}><Panel fill title={`${model.season} versus ${model.seasonComparison.priorSeason}`} note="Unavailable changes are explained rather than inferred."><ComparisonTable metrics={model.seasonComparison.headline} limit={7}/><View style={[styles.note,{marginTop:7}]}><Text>{model.seasonComparison.note||model.seasonComparison.status}</Text></View></Panel></View><View style={{width:"42%",paddingHorizontal:4}}><Panel fill title="Methodology and limitations" note="Released aggregate dashboard values only.">{items.length?items.slice(0,12).map((item,i)=><View key={`${i}-${item}`} style={styles.listItem}><Text style={styles.bullet}>+</Text><Text style={{flex:1,fontSize:6.3}}>{item}</Text></View>):<Text style={styles.panelNote}>Not available</Text>}<View style={[styles.note,{marginTop:6}]}><Text>Not available values remain unavailable. They are not reconstructed for this report.</Text></View></Panel></View></View><View style={{marginTop:8,height:270}}><Panel fill title="Setting comparison" note="Match and training values from the approved prior-season comparison model."><ComparisonTable metrics={model.seasonComparison.settings} limit={6}/></Panel></View><View style={{marginTop:8,height:98}}><Panel fill title="Publication record" note="This information appears on every page for auditability."><View style={styles.split}><View style={styles.half}><Text style={styles.compactLabel}>Report version</Text><Text style={[styles.metricValue,{fontSize:13,marginTop:5}]}>v{meta.version}</Text></View><View style={styles.half}><Text style={styles.compactLabel}>Export date</Text><Text style={[styles.metricValue,{fontSize:13,marginTop:5}]}>{formatDate(meta.exportedAt)}</Text></View></View></Panel></View></PageShell>;}

const sectionPages:Record<ReportSectionId,(model:ReportModel,meta:ReportMetadata)=>ReactElement>={
  cover:(m,x)=><CoverPage model={m} meta={x}/>, "season-pattern":(m,x)=><SeasonPattern model={m} meta={x}/>,
  "severity-contact":(m,x)=><SeverityContact model={m} meta={x}/>, "injury-location":(m,x)=><InjuryLocation model={m} meta={x}/>,
  "common-injuries":(m,x)=><CommonInjuries model={m} meta={x}/>, "impact-matrices":(m,x)=><ImpactMatrices model={m} meta={x}/>,
  "injury-types":(m,x)=><InjuryTypes model={m} meta={x}/>, exposure:(m,x)=><Exposure model={m} meta={x}/>,
  "team-comparison":(m,x)=><TeamComparison model={m} meta={x}/>, "season-methodology":(m,x)=><SeasonMethodology model={m} meta={x}/>,
};
export function enabledReportSections(sectionIds?:readonly ReportSectionId[]){const requested=new Set(sectionIds??DEFAULT_REPORT_SECTION_IDS);return DEFAULT_REPORT_SECTION_IDS.filter((id)=>requested.has(id));}
export function ReportDocument({model,enabledSectionIds}:{model:ReportModel;enabledSectionIds?:readonly ReportSectionId[]}){if(model.schemaVersion!=="urc-report-v1")throw new Error("Unsupported report model schema");const meta=metadata(model);return <Document title={`${model.subjectName} injury surveillance report ${model.season}`} author="United Rugby Championship" subject={`Released aggregate injury surveillance metrics | ${meta.version}`} creator="URC injury surveillance" creationDate={new Date(meta.exportedAt)}>{enabledReportSections(enabledSectionIds).map((section)=>cloneElement(sectionPages[section](model,meta),{key:section}))}</Document>;}
