#!/usr/bin/env python3
"""Deterministically replay the additive, season-bound 2025-26 ledger."""
from __future__ import annotations

import argparse
import hashlib
import importlib.util
import json
from datetime import date, datetime
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SEASON = "2025-26"
WINDOW = {"start": "2025-09-01", "end": "2026-06-30"}


def _module() -> Any:
    spec = importlib.util.spec_from_file_location("frozen_replay", ROOT / "tools/replay.py")
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


FROZEN = _module()


class Year2ReplayError(ValueError):
    pass


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def validate_ledger(ledger: dict[str, Any], master_sha256: str) -> None:
    if ledger.get("season") != SEASON:
        raise Year2ReplayError("Year 2 ledger season must be 2025-26")
    if ledger.get("reporting_window") != WINDOW:
        raise Year2ReplayError("Year 2 ledger must bind the inclusive Sep-Jun reporting window")
    if ledger.get("baseline", {}).get("master", {}).get("sha256") != master_sha256:
        raise Year2ReplayError("Year 2 master checksum does not match the ledger")
    for step in ledger.get("steps", []):
        if step.get("season", SEASON) != SEASON:
            raise Year2ReplayError("Year 2 ledger step is not season-bound")
        for entry in step.get("entries", []):
            if entry.get("season") != SEASON:
                raise Year2ReplayError("Year 2 ledger entry is not season-bound")
            if SEASON not in str(entry.get("evidence_locator", "")):
                raise Year2ReplayError("Year 2 ledger entry evidence locator is not season-bound")


def write_methodology(ledger: dict[str, Any], path: Path) -> None:
    lines = [
        "# URC 2025-26 Inclusion Methodology",
        "",
        "> Generated by `tools/replay_2025_26.py`. Do not edit by hand.",
        "",
        "## Reporting cohort",
        "",
        "The initial reporting cohort is inclusive from 1 September 2025 through 30 June 2026.",
        "July and August 2025 source evidence is retained in the append-only master but excluded from this initial reporting cohort.",
        "Undated season-attributed injuries remain in applicable totals and non-monthly breakdowns, but cannot enter monthly series.",
        "",
        "## Decision ledger",
        "",
        "Only evidence-bound 2025-26 entries are replayed. No 2024-25 row decision is carried forward.",
        "",
    ]
    for step in ledger.get("steps", []):
        lines.extend([f"## {step['order']}. {step['rule_version']}", "", step.get("description", ""), ""])
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def apply_reporting_window(
    headers: list[str], rows: list[list[Any]], source_rows: list[int],
) -> tuple[list[list[Any]], list[int], dict[str, int]]:
    date_index = headers.index("Date Injured")
    window_start = date.fromisoformat(WINDOW["start"])
    window_end = date.fromisoformat(WINDOW["end"])
    retained_rows: list[list[Any]] = []
    retained_source_rows: list[int] = []
    counts = {
        "dated_in_window": 0,
        "dated_outside_window": 0,
        "undated_retained": 0,
    }
    for row, source_row in zip(rows, source_rows, strict=True):
        value = FROZEN.comparison_value(row[date_index]).strip()
        if not value:
            counts["undated_retained"] += 1
            retained_rows.append(row)
            retained_source_rows.append(source_row)
            continue
        parsed = None
        for pattern in ("%Y-%m-%d", "%d/%m/%Y", "%d/%m/%y"):
            try:
                parsed = datetime.strptime(value, pattern).date()
                break
            except ValueError:
                pass
        if parsed is None:
            raise Year2ReplayError(
                f"unparseable Date Injured at master row {source_row}"
            )
        if window_start <= parsed <= window_end:
            counts["dated_in_window"] += 1
            retained_rows.append(row)
            retained_source_rows.append(source_row)
        else:
            counts["dated_outside_window"] += 1
    return retained_rows, retained_source_rows, counts


def replay(master_path: Path, ledger_path: Path, output_path: Path, manifest_path: Path, methodology_path: Path) -> dict[str, Any]:
    master_sha256 = sha256(master_path)
    ledger = json.loads(ledger_path.read_text(encoding="utf-8"))
    validate_ledger(ledger, master_sha256)
    headers, master_rows = FROZEN.load_master_table(json.loads(master_path.read_text(encoding="utf-8")))
    replay_master, preselected, counts, pre_conflicts = FROZEN.apply_exclusion_reason_preselection(headers, master_rows, ledger)
    selected, source_rows = FROZEN.select_inclusion(headers, replay_master)
    rows, included_rows, summaries, conflicts = FROZEN.apply_ledger(headers, selected, source_rows, ledger, replay_master, preselected, counts)
    conflicts = [*pre_conflicts, *conflicts]
    if conflicts:
        raise Year2ReplayError("Year 2 replay produced conflicts; canonical output was not written")
    rows, included_rows, reporting_window_filter = apply_reporting_window(
        headers, rows, included_rows
    )
    FROZEN.EXPORT.write_csv_atomic(output_path, headers, rows)
    payload = {
        "artifact_type": "replayed_included_injury_dataset",
        "season": SEASON,
        "reporting_window": WINDOW,
        "master_sha256": master_sha256,
        "master_rows": len(master_rows),
        "ledger_sha256": sha256(ledger_path),
        "included_rows": len(rows),
        "reporting_window_filter": reporting_window_filter,
        "included_source_rows_sha256": FROZEN.mapping_sha256(included_rows),
        "output_sha256": sha256(output_path),
        "columns": len(headers),
        "replay_counts": summaries,
        "generator": "tools/replay_2025_26.py",
    }
    FROZEN.EXPORT.write_json_atomic(manifest_path, payload)
    write_methodology(ledger, methodology_path)
    return payload


def main() -> int:
    parser = argparse.ArgumentParser(description="Replay the season-bound 2025-26 injury ledger")
    parser.add_argument("--master", type=Path, required=True)
    parser.add_argument("--ledger", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--manifest", type=Path, required=True)
    parser.add_argument("--methodology", type=Path, required=True)
    args = parser.parse_args()
    try:
        print(json.dumps(replay(args.master, args.ledger, args.output, args.manifest, args.methodology), indent=2))
        return 0
    except (OSError, json.JSONDecodeError, Year2ReplayError) as error:
        print(f"ERROR: {error}")
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
